#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <cmath>

#define DEFAULT_HOSTNAME "localhost"
#define DEFAULT_PORT "58037" // 58000 + GN (Our GroupNumber is 37)

#define UDP_TIMEOUT_SECONDS (4)
#define UDP_RESEND_TRIES (3)
#define TCP_READ_TIMEOUT_SECONDS (15)
#define TCP_WRITE_TIMEOUT_SECONDS (20 * 60)  // 20 minutes
#define SERVER_RECV_RESTART_TIMEOUT_SECONDS (3)

#define SOCKET_BUFFER_LEN (256)
#define PACKET_ID_LEN (3)

#define USER_ID_MAX_LEN (6)
#define USER_ID_MAX ((uint32_t)pow(10, USER_ID_MAX_LEN) - 1)
#define PASSWORD_MAX_LEN (8)

#define EXCEPTION_RETRY_MAX (3)

#define FILE_BUFFER_LEN (512)


#define BASE_DIR "ASDIR/"
#define AUCTIONS_DIR "AUCTION/"
#define USERS_DIR "USERS/"


#define HELP_MENU_COMMAND_COLUMN_WIDTH (20)
#define HELP_MENU_DESCRIPTION_COLUMN_WIDTH (40)
#define HELP_MENU_ALIAS_COLUMN_WIDTH (40)

#define TCP_WORKER_POOL_SIZE (50)
#define TCP_MAX_QUEUE_SIZE (5)

#endif